**Practical 01: Python, Excel, Pandas and DataFrame Basics**
Aim
To develop fundamental skills in using Python and Pandas for loading, exploring, inspecting, manipulating, and performing basic analysis of an Excel-based Pharmacognosy dataset in Google Colab.
**Objectives**
By completing this practical, the learner will be able to:

Import and use the Pandas library in Python.
Load an Excel dataset directly from a GitHub repository.
Create and understand a Pandas DataFrame.
Display and inspect the contents of an Excel dataset.
Determine the number of rows and columns in a dataset.
Identify and work with column names.
Understand different data types in a DataFrame.
Inspect the structure and information of a dataset.
View the first and last records of a dataset.
Select specific rows and columns.
Filter records based on conditions.
Add, modify, rename, and delete DataFrame columns.
Sort and organize DataFrame records.
Identify missing values and duplicated records.
Perform basic descriptive statistical analysis.
Save and export processed data when required.
Learning Outcomes

After completing this practical, the learner will be able to independently load an Excel dataset from GitHub into Google Colab, understand its structure, inspect and manipulate DataFrames, identify data-quality issues, perform basic exploratory operations, and prepare a dataset for subsequent data preprocessing and machine-learning applications.

In [1]:
# Import Pandas
import pandas as pd

# GitHub RAW URL of the Excel file
url = "https://raw.githubusercontent.com/drpharmacy/pharma-ml-projects/main/Excel_Files/Pharmacognosy_ML_Master_Dataset.xlsx"

# Load Excel file into a Pandas DataFrame
df = pd.read_excel(url)

# Display the first 5 rows
df.head()

,Sample_ID,Plant_Name,Family,Plant_Part,Solvent,Extraction_Method,Collection_Season,Temperature_C,Extraction_Time_h,Solvent_to_Drug_Ratio,Moisture_Content_pct,Ash_Value_pct,Extractive_Value_pct,Total_Phenolic_Content_mg_GAE_g,Total_Flavonoid_Content_mg_QE_g,Antioxidant_Activity_pct,Marker_Compound_pct,Extraction_Yield_pct,Quality_Class,Antioxidant_Class
0,PG001,Bacopa monnieri,Plantaginaceae,Seed,Ethanol,Maceration,Monsoon,51,2,12.6,12.24,5.46,16.02,111.69,59.83,31.59,0.510,13.58,Low,Less_Active
1,PG002,Tinospora cordifolia,Menispermaceae,Rhizome,Hydroalcoholic,Soxhlet,Winter,43,2,13.9,17.75,9.76,25.53,169.24,88.33,49.06,4.912,17.45,Low,Less_Active
2,PG003,Aloe vera,Asphodelaceae,Leaf,Hydroalcoholic,Maceration,Summer,55,8,10.1,16.38,11.41,16.87,112.03,46.21,44.77,7.278,17.31,Low,Less_Active
3,PG004,Curcuma longa,Zingiberaceae,Leaf,Methanol,Maceration,Summer,57,3,13.5,12.41,2.72,25.02,96.70,20.28,52.35,2.063,15.17,Low,Less_Active
4,PG005,Bacopa monnieri,Plantaginaceae,Stem,Water,Soxhlet,Summer,52,6,18.3,16.65,7.34,24.47,70.20,58.01,80.88,3.863,13.38,Low,Active

**Meaning of block 1**: This code imports the Pandas library and gives it the short name pd, stores the RAW GitHub location of our master Excel file in the variable url, and uses pd.read_excel() to read the Excel file directly from GitHub into a Pandas DataFrame called df. The command df.head() displays the first five rows so that we can confirm that the dataset has been loaded correctly. This same df will be used for our subsequent data-handling and machine-learning operations.

In [2]:
# Block 2: Inspecting the DataFrame Structure

print("Shape of dataset:", df.shape)

print("\nColumn names:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nDataFrame information:")
df.info()

Shape of dataset: (200, 20)

Column names:
['Sample_ID', 'Plant_Name', 'Family', 'Plant_Part', 'Solvent', 'Extraction_Method', 'Collection_Season', 'Temperature_C', 'Extraction_Time_h', 'Solvent_to_Drug_Ratio', 'Moisture_Content_pct', 'Ash_Value_pct', 'Extractive_Value_pct', 'Total_Phenolic_Content_mg_GAE_g', 'Total_Flavonoid_Content_mg_QE_g', 'Antioxidant_Activity_pct', 'Marker_Compound_pct', 'Extraction_Yield_pct', 'Quality_Class', 'Antioxidant_Class']

Data types:
Sample_ID                           object
Plant_Name                          object
Family                              object
Plant_Part                          object
Solvent                             object
Extraction_Method                   object
Collection_Season                   object
Temperature_C                        int64
Extraction_Time_h                    int64
Solvent_to_Drug_Ratio              float64
Moisture_Content_pct               float64
Ash_Value_pct                      float64
Extractive_Value_pct               float64
Total_Phenolic_Content_mg_GAE_g    float64
Total_Flavonoid_Content_mg_QE_g    float64
Antioxidant_Activity_pct           float64
Marker_Compound_pct                float64
Extraction_Yield_pct               float64
Quality_Class                       object
Antioxidant_Class                   object
dtype: object

DataFrame information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 20 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Sample_ID                        200 non-null    object
 1   Plant_Name                       200 non-null    object
 2   Family                           200 non-null    object
 3   Plant_Part                       200 non-null    object
 4   Solvent                          200 non-null    object
 5   Extraction_Method                200 non-null    object
 6   Collection_Season                200 non-null    object
 7   Temperature_C                    200 non-null    int64
 8   Extraction_Time_h                200 non-null    int64
 9   Solvent_to_Drug_Ratio            200 non-null    float64
 10  Moisture_Content_pct             196 non-null    float64
 11  Ash_Value_pct                    200 non-null    float64
 12  Extractive_Value_pct             200 non-null    float64
 13  Total_Phenolic_Content_mg_GAE_g  196 non-null    float64
 14  Total_Flavonoid_Content_mg_QE_g  200 non-null    float64
 15  Antioxidant_Activity_pct         200 non-null    float64
 16  Marker_Compound_pct              196 non-null    float64
 17  Extraction_Yield_pct             200 non-null    float64
 18  Quality_Class                    200 non-null    object
 19  Antioxidant_Class                200 non-null    object
dtypes: float64(9), int64(2), object(9)
memory usage: 31.4+ KB

**Meaning of Code Block 2**

This code block examines the basic structure of the dataset. df.shape displays the number of rows and columns, df.columns.tolist() displays all column names, df.dtypes shows the data type of each column, and df.info() provides a concise summary of the DataFrame, including the number of records, columns, non-null values, and data types. These commands help us understand the dataset before performing data cleaning, preprocessing, visualization, and machine learning.

In [3]:
# Block 3: Viewing the Dataset

print("First 5 rows:")
display(df.head())

print("\nFirst 10 rows:")
display(df.head(10))

print("\nLast 5 rows:")
display(df.tail())

print("\nLast 10 rows:")
display(df.tail(10))

First 5 rows:

,Sample_ID,Plant_Name,Family,Plant_Part,Solvent,Extraction_Method,Collection_Season,Temperature_C,Extraction_Time_h,Solvent_to_Drug_Ratio,Moisture_Content_pct,Ash_Value_pct,Extractive_Value_pct,Total_Phenolic_Content_mg_GAE_g,Total_Flavonoid_Content_mg_QE_g,Antioxidant_Activity_pct,Marker_Compound_pct,Extraction_Yield_pct,Quality_Class,Antioxidant_Class
0,PG001,Bacopa monnieri,Plantaginaceae,Seed,Ethanol,Maceration,Monsoon,51,2,12.6,12.24,5.46,16.02,111.69,59.83,31.59,0.510,13.58,Low,Less_Active
1,PG002,Tinospora cordifolia,Menispermaceae,Rhizome,Hydroalcoholic,Soxhlet,Winter,43,2,13.9,17.75,9.76,25.53,169.24,88.33,49.06,4.912,17.45,Low,Less_Active
2,PG003,Aloe vera,Asphodelaceae,Leaf,Hydroalcoholic,Maceration,Summer,55,8,10.1,16.38,11.41,16.87,112.03,46.21,44.77,7.278,17.31,Low,Less_Active
3,PG004,Curcuma longa,Zingiberaceae,Leaf,Methanol,Maceration,Summer,57,3,13.5,12.41,2.72,25.02,96.70,20.28,52.35,2.063,15.17,Low,Less_Active
4,PG005,Bacopa monnieri,Plantaginaceae,Stem,Water,Soxhlet,Summer,52,6,18.3,16.65,7.34,24.47,70.20,58.01,80.88,3.863,13.38,Low,Active

First 10 rows:

,Sample_ID,Plant_Name,Family,Plant_Part,Solvent,Extraction_Method,Collection_Season,Temperature_C,Extraction_Time_h,Solvent_to_Drug_Ratio,Moisture_Content_pct,Ash_Value_pct,Extractive_Value_pct,Total_Phenolic_Content_mg_GAE_g,Total_Flavonoid_Content_mg_QE_g,Antioxidant_Activity_pct,Marker_Compound_pct,Extraction_Yield_pct,Quality_Class,Antioxidant_Class
0,PG001,Bacopa monnieri,Plantaginaceae,Seed,Ethanol,Maceration,Monsoon,51,2,12.6,12.24,5.46,16.02,111.69,59.83,31.59,0.510,13.58,Low,Less_Active
1,PG002,Tinospora cordifolia,Menispermaceae,Rhizome,Hydroalcoholic,Soxhlet,Winter,43,2,13.9,17.75,9.76,25.53,169.24,88.33,49.06,4.912,17.45,Low,Less_Active
2,PG003,Aloe vera,Asphodelaceae,Leaf,Hydroalcoholic,Maceration,Summer,55,8,10.1,16.38,11.41,16.87,112.03,46.21,44.77,7.278,17.31,Low,Less_Active
3,PG004,Curcuma longa,Zingiberaceae,Leaf,Methanol,Maceration,Summer,57,3,13.5,12.41,2.72,25.02,96.70,20.28,52.35,2.063,15.17,Low,Less_Active
4,PG005,Bacopa monnieri,Plantaginaceae,Stem,Water,Soxhlet,Summer,52,6,18.3,16.65,7.34,24.47,70.20,58.01,80.88,3.863,13.38,Low,Active
5,PG006,Gmelina arborea,Lamiaceae,Rhizome,Water,Reflux,Summer,43,9,13.4,17.85,10.83,23.21,117.02,82.12,51.04,3.714,16.03,Low,Less_Active
6,PG007,Ocimum tenuiflorum,Lamiaceae,Seed,Water,Reflux,Summer,53,9,15.8,14.41,2.83,18.27,42.27,75.46,56.62,3.889,23.06,Low,Less_Active
7,PG008,Bacopa monnieri,Plantaginaceae,Bark,Hydroalcoholic,Maceration,Summer,31,4,17.1,4.91,10.25,22.81,163.72,88.74,52.82,5.056,13.43,Medium,Less_Active
8,PG009,Aloe vera,Asphodelaceae,Rhizome,Hydroalcoholic,Soxhlet,Summer,74,8,19.8,9.62,5.58,24.11,152.69,31.40,31.54,3.864,19.60,Low,Less_Active
9,PG010,Curcuma longa,Zingiberaceae,Stem,Hydroalcoholic,Maceration,Monsoon,55,4,14.0,15.73,5.22,22.73,70.81,23.43,55.88,3.690,19.61,Low,Less_Active

Last 5 rows:

,Sample_ID,Plant_Name,Family,Plant_Part,Solvent,Extraction_Method,Collection_Season,Temperature_C,Extraction_Time_h,Solvent_to_Drug_Ratio,Moisture_Content_pct,Ash_Value_pct,Extractive_Value_pct,Total_Phenolic_Content_mg_GAE_g,Total_Flavonoid_Content_mg_QE_g,Antioxidant_Activity_pct,Marker_Compound_pct,Extraction_Yield_pct,Quality_Class,Antioxidant_Class
195,PG196,Aloe vera,Asphodelaceae,Stem,Water,Maceration,Summer,62,8,10.9,5.44,11.01,16.71,138.95,94.93,93.87,6.018,17.31,Medium,Active
196,PG197,Curcuma longa,Zingiberaceae,Stem,Ethanol,Maceration,Winter,52,4,6.9,11.99,10.78,8.62,117.91,58.22,43.83,4.485,12.01,Low,Less_Active
197,PG198,Tinospora cordifolia,Menispermaceae,Bark,Water,Reflux,Summer,44,9,19.3,4.26,5.17,12.15,36.95,76.32,53.49,0.650,17.36,Low,Less_Active
198,PG199,Withania somnifera,Solanaceae,Stem,Ethanol,Reflux,Winter,62,8,17.0,10.75,10.69,14.04,44.25,58.01,87.40,5.510,20.68,Medium,Active
199,PG200,Glycyrrhiza glabra,Fabaceae,Seed,Water,Ultrasound,Winter,54,12,8.9,6.94,5.76,33.85,35.00,57.49,25.20,3.841,24.49,Low,Less_Active

Last 10 rows:

,Sample_ID,Plant_Name,Family,Plant_Part,Solvent,Extraction_Method,Collection_Season,Temperature_C,Extraction_Time_h,Solvent_to_Drug_Ratio,Moisture_Content_pct,Ash_Value_pct,Extractive_Value_pct,Total_Phenolic_Content_mg_GAE_g,Total_Flavonoid_Content_mg_QE_g,Antioxidant_Activity_pct,Marker_Compound_pct,Extraction_Yield_pct,Quality_Class,Antioxidant_Class
190,PG191,Tinospora cordifolia,Menispermaceae,Stem,Methanol,Soxhlet,Winter,69,3,13.8,17.34,3.09,22.38,98.14,6.70,80.07,4.826,17.23,Low,Active
191,PG192,Bacopa monnieri,Plantaginaceae,Bark,Hydroalcoholic,Reflux,Summer,43,8,9.2,16.71,8.51,27.48,44.11,16.99,92.95,4.873,17.46,Medium,Active
192,PG193,Aloe vera,Asphodelaceae,Leaf,Ethanol,Soxhlet,Summer,61,9,18.7,14.14,9.65,11.81,74.78,67.66,43.39,2.957,20.24,Low,Less_Active
193,PG194,Azadirachta indica,Meliaceae,Bark,Hydroalcoholic,Reflux,Monsoon,80,2,5.7,14.49,11.26,13.72,86.15,20.35,44.01,3.776,18.15,Low,Less_Active
194,PG195,Glycyrrhiza glabra,Fabaceae,Stem,Ethanol,Reflux,Summer,67,10,6.6,6.04,6.38,30.11,141.31,29.27,58.10,0.496,21.23,Low,Less_Active
195,PG196,Aloe vera,Asphodelaceae,Stem,Water,Maceration,Summer,62,8,10.9,5.44,11.01,16.71,138.95,94.93,93.87,6.018,17.31,Medium,Active
196,PG197,Curcuma longa,Zingiberaceae,Stem,Ethanol,Maceration,Winter,52,4,6.9,11.99,10.78,8.62,117.91,58.22,43.83,4.485,12.01,Low,Less_Active
197,PG198,Tinospora cordifolia,Menispermaceae,Bark,Water,Reflux,Summer,44,9,19.3,4.26,5.17,12.15,36.95,76.32,53.49,0.650,17.36,Low,Less_Active
198,PG199,Withania somnifera,Solanaceae,Stem,Ethanol,Reflux,Winter,62,8,17.0,10.75,10.69,14.04,44.25,58.01,87.40,5.510,20.68,Medium,Active
199,PG200,Glycyrrhiza glabra,Fabaceae,Seed,Water,Ultrasound,Winter,54,12,8.9,6.94,5.76,33.85,35.00,57.49,25.20,3.841,24.49,Low,Less_Active

**Meaning of Code Block 3**

This code block is used to view records from the beginning and end of the DataFrame. df.head() displays the first five rows by default, while df.head(10) displays the first ten rows. Similarly, df.tail() displays the last five rows and df.tail(10) displays the last ten rows. The display() function provides a clean tabular representation in Google Colab. These commands are useful for quickly checking whether the dataset has loaded correctly and for inspecting the actual records before further analysis.

In [4]:
# Block 4: Selecting Columns from the DataFrame

# Select a single column
print("Plant names:")
display(df["Plant_Name"])

# Select multiple columns
print("Selected columns:")
display(df[["Plant_Name", "Family", "Plant_Part", "Extraction_Method"]])

# Check the data type of a selected column
print("Data type of Extraction Yield:")
print(df["Extraction_Yield_pct"].dtype)

Plant names:

0           Bacopa monnieri
1      Tinospora cordifolia
2                 Aloe vera
3             Curcuma longa
4           Bacopa monnieri
               ...
195               Aloe vera
196           Curcuma longa
197    Tinospora cordifolia
198      Withania somnifera
199      Glycyrrhiza glabra
Name: Plant_Name, Length: 200, dtype: object

Selected columns:

               Plant_Name          Family Plant_Part Extraction_Method
0         Bacopa monnieri  Plantaginaceae       Seed        Maceration
1    Tinospora cordifolia  Menispermaceae    Rhizome           Soxhlet
2               Aloe vera   Asphodelaceae       Leaf        Maceration
3           Curcuma longa   Zingiberaceae       Leaf        Maceration
4         Bacopa monnieri  Plantaginaceae       Stem           Soxhlet
..                    ...             ...        ...               ...
195             Aloe vera   Asphodelaceae       Stem        Maceration
196         Curcuma longa   Zingiberaceae       Stem        Maceration
197  Tinospora cordifolia  Menispermaceae       Bark            Reflux
198    Withania somnifera      Solanaceae       Stem            Reflux
199    Glycyrrhiza glabra        Fabaceae       Seed        Ultrasound

[200 rows x 4 columns]

Data type of Extraction Yield:
float64

**Meaning of Code Block 4**

This code block teaches how to select individual or multiple columns from a Pandas DataFrame. df["Plant_Name"] selects one column, while df[["Plant_Name", "Family", "Plant_Part", "Extraction_Method"]] selects several columns together and returns them as a new DataFrame. The dtype command shows the data type of a particular column, which is important for deciding how that variable can be used during data analysis and machine learning.

In [5]:
# Block 5: Selecting Rows and Specific Data

# Select the first row
print("First row:")
display(df.iloc[0])

# Select the first five rows
print("First five rows:")
display(df.iloc[0:5])

# Select rows 0 to 4 and columns 0 to 3
print("Selected rows and columns:")
display(df.iloc[0:5, 0:4])

# Select a specific cell
print("Value of first row, Plant Name column:")
print(df.iloc[0]["Plant_Name"])

First row:

Sample_ID                                    PG001
Plant_Name                         Bacopa monnieri
Family                              Plantaginaceae
Plant_Part                                    Seed
Solvent                                    Ethanol
Extraction_Method                       Maceration
Collection_Season                          Monsoon
Temperature_C                                   51
Extraction_Time_h                                2
Solvent_to_Drug_Ratio                         12.6
Moisture_Content_pct                         12.24
Ash_Value_pct                                 5.46
Extractive_Value_pct                         16.02
Total_Phenolic_Content_mg_GAE_g             111.69
Total_Flavonoid_Content_mg_QE_g              59.83
Antioxidant_Activity_pct                     31.59
Marker_Compound_pct                           0.51
Extraction_Yield_pct                         13.58
Quality_Class                                  Low
Antioxidant_Class                      Less_Active
Name: 0, dtype: object

First five rows:

,Sample_ID,Plant_Name,Family,Plant_Part,Solvent,Extraction_Method,Collection_Season,Temperature_C,Extraction_Time_h,Solvent_to_Drug_Ratio,Moisture_Content_pct,Ash_Value_pct,Extractive_Value_pct,Total_Phenolic_Content_mg_GAE_g,Total_Flavonoid_Content_mg_QE_g,Antioxidant_Activity_pct,Marker_Compound_pct,Extraction_Yield_pct,Quality_Class,Antioxidant_Class
0,PG001,Bacopa monnieri,Plantaginaceae,Seed,Ethanol,Maceration,Monsoon,51,2,12.6,12.24,5.46,16.02,111.69,59.83,31.59,0.510,13.58,Low,Less_Active
1,PG002,Tinospora cordifolia,Menispermaceae,Rhizome,Hydroalcoholic,Soxhlet,Winter,43,2,13.9,17.75,9.76,25.53,169.24,88.33,49.06,4.912,17.45,Low,Less_Active
2,PG003,Aloe vera,Asphodelaceae,Leaf,Hydroalcoholic,Maceration,Summer,55,8,10.1,16.38,11.41,16.87,112.03,46.21,44.77,7.278,17.31,Low,Less_Active
3,PG004,Curcuma longa,Zingiberaceae,Leaf,Methanol,Maceration,Summer,57,3,13.5,12.41,2.72,25.02,96.70,20.28,52.35,2.063,15.17,Low,Less_Active
4,PG005,Bacopa monnieri,Plantaginaceae,Stem,Water,Soxhlet,Summer,52,6,18.3,16.65,7.34,24.47,70.20,58.01,80.88,3.863,13.38,Low,Active

Selected rows and columns:

  Sample_ID            Plant_Name          Family Plant_Part
0     PG001       Bacopa monnieri  Plantaginaceae       Seed
1     PG002  Tinospora cordifolia  Menispermaceae    Rhizome
2     PG003             Aloe vera   Asphodelaceae       Leaf
3     PG004         Curcuma longa   Zingiberaceae       Leaf
4     PG005       Bacopa monnieri  Plantaginaceae       Stem

Value of first row, Plant Name column:
Bacopa monnieri

**Meaning of Code Block 5**

This code block demonstrates how to select specific rows and individual data values using Pandas. df.iloc[0] selects the first row, df.iloc[0:5] selects the first five rows, and df.iloc[0:5, 0:4] selects rows 0 to 4 and columns 0 to 3 using integer-based indexing. The expression df.iloc[0]["Plant_Name"] retrieves a particular value from the DataFrame. Understanding row and column selection is essential for examining, manipulating, and preparing datasets for machine learning.

In [6]:
# Block 6: Filtering Rows Using Conditions

# Select samples with extraction yield greater than 25%
high_yield = df[df["Extraction_Yield_pct"] > 25]
display(high_yield)

# Select samples extracted using ethanol
ethanol_samples = df[df["Solvent"] == "Ethanol"]
display(ethanol_samples)

# Select samples with antioxidant activity greater than or equal to 60%
active_samples = df[df["Antioxidant_Activity_pct"] >= 60]
display(active_samples)

# Apply two conditions together
selected_samples = df[
    (df["Extraction_Yield_pct"] > 25) &
    (df["Antioxidant_Activity_pct"] >= 60)
]
display(selected_samples)

,Sample_ID,Plant_Name,Family,Plant_Part,Solvent,Extraction_Method,Collection_Season,Temperature_C,Extraction_Time_h,Solvent_to_Drug_Ratio,Moisture_Content_pct,Ash_Value_pct,Extractive_Value_pct,Total_Phenolic_Content_mg_GAE_g,Total_Flavonoid_Content_mg_QE_g,Antioxidant_Activity_pct,Marker_Compound_pct,Extraction_Yield_pct,Quality_Class,Antioxidant_Class
97,PG098,Bacopa monnieri,Plantaginaceae,Root,Methanol,Reflux,Winter,67,8,19.3,4.26,8.63,13.57,64.7,40.81,85.65,1.965,25.32,Low,Active

,Sample_ID,Plant_Name,Family,Plant_Part,Solvent,Extraction_Method,Collection_Season,Temperature_C,Extraction_Time_h,Solvent_to_Drug_Ratio,Moisture_Content_pct,Ash_Value_pct,Extractive_Value_pct,Total_Phenolic_Content_mg_GAE_g,Total_Flavonoid_Content_mg_QE_g,Antioxidant_Activity_pct,Marker_Compound_pct,Extraction_Yield_pct,Quality_Class,Antioxidant_Class
0,PG001,Bacopa monnieri,Plantaginaceae,Seed,Ethanol,Maceration,Monsoon,51,2,12.6,12.24,5.46,16.02,111.69,59.83,31.59,0.510,13.58,Low,Less_Active
10,PG011,Tinospora cordifolia,Menispermaceae,Stem,Ethanol,Ultrasound,Winter,43,7,17.1,7.23,11.77,20.00,172.45,88.58,38.69,3.899,20.85,Low,Less_Active
16,PG017,Withania somnifera,Solanaceae,Rhizome,Ethanol,Maceration,Winter,75,11,6.3,17.40,11.52,21.51,57.21,70.35,46.86,6.783,22.49,Low,Less_Active
24,PG025,Moringa oleifera,Moringaceae,Stem,Ethanol,Reflux,Summer,44,10,18.7,7.64,11.47,22.22,156.23,76.21,67.94,6.570,18.37,Medium,Active
26,PG027,Gmelina arborea,Lamiaceae,Leaf,Ethanol,Ultrasound,Summer,66,6,10.0,10.88,9.83,20.87,22.83,69.45,87.80,6.582,21.36,Medium,Active
30,PG031,Moringa oleifera,Moringaceae,Rhizome,Ethanol,Maceration,Winter,46,5,17.5,NaN,7.53,27.32,110.31,52.69,27.34,0.431,18.51,Low,Less_Active
32,PG033,Curcuma longa,Zingiberaceae,Root,Ethanol,Ultrasound,Winter,51,3,16.6,4.49,9.84,30.20,53.88,41.61,76.28,0.550,18.44,Low,Active
33,PG034,Ocimum tenuiflorum,Lamiaceae,Leaf,Ethanol,Reflux,Summer,55,11,10.4,16.53,6.81,19.63,97.54,66.12,82.43,3.715,20.84,Medium,Active
36,PG037,Moringa oleifera,Moringaceae,Leaf,Ethanol,Ultrasound,Summer,46,11,19.6,9.48,6.39,33.78,67.58,18.09,92.74,3.241,22.51,Medium,Active
43,PG044,Moringa oleifera,Moringaceae,Rhizome,Ethanol,Ultrasound,Monsoon,70,9,12.3,17.04,6.70,24.67,130.66,41.83,33.57,5.804,22.60,Low,Less_Active
45,PG046,Curcuma longa,Zingiberaceae,Leaf,Ethanol,Maceration,Winter,47,6,16.1,7.94,10.72,26.09,121.31,88.05,47.61,5.827,15.11,Medium,Less_Active
46,PG047,Withania somnifera,Solanaceae,Rhizome,Ethanol,Soxhlet,Winter,76,5,15.5,7.54,6.34,33.10,56.62,53.46,94.80,6.930,19.36,Medium,Active
47,PG048,Tinospora cordifolia,Menispermaceae,Rhizome,Ethanol,Soxhlet,Summer,65,3,11.0,4.07,2.44,22.37,57.22,73.72,93.58,0.216,20.01,Low,Active
49,PG050,Aloe vera,Asphodelaceae,Stem,Ethanol,Soxhlet,Winter,51,4,14.7,4.68,2.21,10.42,47.80,26.42,34.09,6.671,13.67,Low,Less_Active
53,PG054,Withania somnifera,Solanaceae,Rhizome,Ethanol,Ultrasound,Winter,69,11,15.4,16.52,6.93,30.23,146.73,61.94,82.61,5.389,23.69,Medium,Active
55,PG056,Tinospora cordifolia,Menispermaceae,Stem,Ethanol,Maceration,Monsoon,73,12,17.3,4.86,6.03,11.33,124.65,7.18,51.53,5.369,21.87,Medium,Less_Active
62,PG063,Withania somnifera,Solanaceae,Rhizome,Ethanol,Soxhlet,Monsoon,63,7,15.8,16.10,6.16,32.78,59.77,24.93,94.16,6.049,17.23,Medium,Active
64,PG065,Withania somnifera,Solanaceae,Bark,Ethanol,Reflux,Winter,35,8,7.1,11.30,8.29,10.35,86.97,54.43,70.62,5.240,14.61,Low,Active
65,PG066,Gmelina arborea,Lamiaceae,Root,Ethanol,Maceration,Summer,66,11,9.0,16.15,9.35,30.03,146.45,40.48,46.98,5.242,17.84,Low,Less_Active
68,PG069,Bacopa monnieri,Plantaginaceae,Root,Ethanol,Ultrasound,Summer,50,9,8.8,6.25,7.43,11.03,50.35,27.41,86.59,4.117,19.67,Medium,Active
70,PG071,Aloe vera,Asphodelaceae,Rhizome,Ethanol,Maceration,Summer,35,10,12.4,7.34,7.88,25.23,71.76,10.94,42.10,1.103,16.34,Low,Less_Active
75,PG076,Gmelina arborea,Lamiaceae,Stem,Ethanol,Ultrasound,Summer,59,5,11.3,16.34,9.93,12.72,26.82,21.48,88.38,4.334,18.44,Medium,Active
81,PG082,Moringa oleifera,Moringaceae,Leaf,Ethanol,Soxhlet,Monsoon,60,2,6.0,7.20,6.66,16.16,43.88,75.99,76.66,3.701,19.23,Low,Active
84,PG085,Aloe vera,Asphodelaceae,Rhizome,Ethanol,Reflux,Monsoon,65,7,18.7,11.79,9.76,26.13,58.96,24.28,42.78,7.299,20.95,Low,Less_Active
87,PG088,Azadirachta indica,Meliaceae,Seed,Ethanol,Soxhlet,Monsoon,35,10,19.2,6.70,8.33,12.04,118.25,20.70,32.44,NaN,21.70,Low,Less_Active
92,PG093,Curcuma longa,Zingiberaceae,Bark,Ethanol,Maceration,Monsoon,33,6,9.0,9.27,6.37,20.77,36.34,93.31,70.87,3.350,15.43,Medium,Active
102,PG103,Bacopa monnieri,Plantaginaceae,Leaf,Ethanol,Soxhlet,Monsoon,37,4,10.3,14.55,10.58,11.83,99.27,72.07,53.58,0.971,16.41,Low,Less_Active
104,PG105,Aloe vera,Asphodelaceae,Stem,Ethanol,Ultrasound,Winter,80,6,15.6,6.43,7.88,24.12,92.02,9.73,88.25,0.296,23.80,Low,Active
105,PG106,Curcuma longa,Zingiberaceae,Bark,Ethanol,Soxhlet,Winter,74,10,14.0,14.79,7.99,26.25,56.31,90.87,41.29,3.086,21.99,Low,Less_Active
112,PG113,Curcuma longa,Zingiberaceae,Stem,Ethanol,Maceration,Monsoon,49,11,6.5,5.05,6.49,24.29,27.65,42.89,36.84,0.549,18.23,Low,Less_Active
123,PG124,Bacopa monnieri,Plantaginaceae,Leaf,Ethanol,Ultrasound,Monsoon,40,12,16.4,15.46,7.34,19.95,175.32,40.26,26.90,6.808,19.88,Low,Less_Active
124,PG125,Azadirachta indica,Meliaceae,Seed,Ethanol,Maceration,Winter,65,3,15.9,7.54,9.82,30.46,170.77,45.74,92.64,4.342,12.78,Medium,Active
125,PG126,Tinospora cordifolia,Menispermaceae,Bark,Ethanol,Ultrasound,Monsoon,42,12,14.6,4.01,9.05,26.08,145.41,85.25,33.92,6.765,22.14,Medium,Less_Active
128,PG129,Bacopa monnieri,Plantaginaceae,Leaf,Ethanol,Soxhlet,Summer,62,12,14.7,17.22,7.58,15.32,107.94,86.04,82.82,1.021,21.15,Low,Active
131,PG132,Bacopa monnieri,Plantaginaceae,Bark,Ethanol,Reflux,Summer,39,7,15.0,11.38,11.87,14.23,87.89,58.39,93.73,1.982,17.16,Low,Active
132,PG133,Ocimum tenuiflorum,Lamiaceae,Leaf,Ethanol,Maceration,Monsoon,34,9,5.7,15.56,3.23,20.34,33.22,37.86,68.49,7.824,10.63,Medium,Active
137,PG138,Curcuma longa,Zingiberaceae,Seed,Ethanol,Maceration,Summer,42,6,9.7,5.84,3.80,34.88,176.16,74.58,56.49,7.420,17.56,Medium,Less_Active
138,PG139,Glycyrrhiza glabra,Fabaceae,Root,Ethanol,Soxhlet,Monsoon,69,9,6.8,16.15,2.89,20.05,126.78,57.09,40.29,3.430,21.44,Low,Less_Active
143,PG144,Bacopa monnieri,Plantaginaceae,Root,Ethanol,Maceration,Winter,38,11,16.9,16.00,6.80,25.14,173.57,79.83,64.70,1.214,16.37,Low,Active
148,PG149,Tinospora cordifolia,Menispermaceae,Leaf,Ethanol,Soxhlet,Winter,53,2,14.7,8.49,7.80,30.19,95.89,73.89,76.12,3.664,17.67,Low,Active
151,PG152,Bacopa monnieri,Plantaginaceae,Rhizome,Ethanol,Reflux,Monsoon,59,2,13.4,6.81,5.43,34.49,167.25,34.33,86.41,0.888,18.87,Low,Active
158,PG159,Gmelina arborea,Lamiaceae,Leaf,Ethanol,Soxhlet,Summer,40,2,17.1,6.85,3.62,28.75,35.20,13.44,83.67,3.927,17.95,Low,Active
162,PG163,Moringa oleifera,Moringaceae,Leaf,Ethanol,Soxhlet,Summer,64,9,12.8,11.42,4.35,14.94,46.19,26.60,80.24,6.741,22.30,Low,Active
164,PG165,Azadirachta indica,Meliaceae,Bark,Ethanol,Ultrasound,Monsoon,30,2,18.1,15.16,4.55,31.35,NaN,56.54,71.12,6.649,13.41,Medium,Active
166,PG167,Gmelina arborea,Lamiaceae,Leaf,Ethanol,Maceration,Summer,51,4,11.9,16.77,11.79,21.68,99.37,57.14,40.42,1.582,13.57,Low,Less_Active
169,PG170,Withania somnifera,Solanaceae,Stem,Ethanol,Ultrasound,Monsoon,40,4,7.8,10.47,4.44,11.18,127.43,85.46,61.77,2.033,17.76,Low,Active
170,PG171,Ocimum tenuiflorum,Lamiaceae,Rhizome,Ethanol,Reflux,Summer,70,3,10.8,4.02,10.31,14.14,70.71,45.72,27.29,6.679,17.13,Low,Less_Active
171,PG172,Azadirachta indica,Meliaceae,Stem,Ethanol,Ultrasound,Summer,66,3,19.0,12.38,10.65,17.23,160.68,18.39,85.80,4.450,17.81,Medium,Active
172,PG173,Curcuma longa,Zingiberaceae,Root,Ethanol,Maceration,Summer,43,7,6.1,12.50,9.69,18.28,61.35,68.10,29.53,1.489,12.51,Low,Less_Active
175,PG176,Azadirachta indica,Meliaceae,Rhizome,Ethanol,Soxhlet,Monsoon,50,7,6.3,7.16,11.19,21.76,55.37,86.89,73.61,1.374,16.63,Low,Active
176,PG177,Azadirachta indica,Meliaceae,Leaf,Ethanol,Reflux,Summer,66,4,5.6,6.25,8.01,30.28,176.54,48.72,30.75,6.571,20.29,Low,Less_Active
180,PG181,Bacopa monnieri,Plantaginaceae,Seed,Ethanol,Reflux,Winter,55,8,11.0,10.07,7.77,12.37,28.62,15.63,48.86,2.544,20.99,Low,Less_Active
185,PG186,Withania somnifera,Solanaceae,Stem,Ethanol,Soxhlet,Summer,54,4,5.1,9.54,10.66,21.53,136.47,37.28,80.22,1.354,17.88,Low,Active
192,PG193,Aloe vera,Asphodelaceae,Leaf,Ethanol,Soxhlet,Summer,61,9,18.7,14.14,9.65,11.81,74.78,67.66,43.39,2.957,20.24,Low,Less_Active
194,PG195,Glycyrrhiza glabra,Fabaceae,Stem,Ethanol,Reflux,Summer,67,10,6.6,6.04,6.38,30.11,141.31,29.27,58.10,0.496,21.23,Low,Less_Active
196,PG197,Curcuma longa,Zingiberaceae,Stem,Ethanol,Maceration,Winter,52,4,6.9,11.99,10.78,8.62,117.91,58.22,43.83,4.485,12.01,Low,Less_Active
198,PG199,Withania somnifera,Solanaceae,Stem,Ethanol,Reflux,Winter,62,8,17.0,10.75,10.69,14.04,44.25,58.01,87.40,5.510,20.68,Medium,Active

,Sample_ID,Plant_Name,Family,Plant_Part,Solvent,Extraction_Method,Collection_Season,Temperature_C,Extraction_Time_h,Solvent_to_Drug_Ratio,Moisture_Content_pct,Ash_Value_pct,Extractive_Value_pct,Total_Phenolic_Content_mg_GAE_g,Total_Flavonoid_Content_mg_QE_g,Antioxidant_Activity_pct,Marker_Compound_pct,Extraction_Yield_pct,Quality_Class,Antioxidant_Class
4,PG005,Bacopa monnieri,Plantaginaceae,Stem,Water,Soxhlet,Summer,52,6,18.3,16.65,7.34,24.47,70.20,58.01,80.88,3.863,13.38,Low,Active
14,PG015,Glycyrrhiza glabra,Fabaceae,Root,Methanol,Reflux,Winter,76,4,11.1,9.38,2.41,25.35,96.52,82.44,78.02,0.586,19.11,Low,Active
17,PG018,Aloe vera,Asphodelaceae,Stem,Hydroalcoholic,Ultrasound,Summer,72,5,14.5,15.57,3.24,22.64,32.79,40.65,69.99,2.422,18.90,Medium,Active
19,PG020,Withania somnifera,Solanaceae,Leaf,Water,Maceration,Monsoon,74,5,17.7,12.82,7.95,30.87,39.53,54.80,87.79,3.621,17.67,Low,Active
20,PG021,Curcuma longa,Zingiberaceae,Leaf,Hydroalcoholic,Ultrasound,Monsoon,47,8,6.8,7.03,8.17,32.68,115.09,85.56,61.41,1.904,21.38,Low,Active
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,PG188,Gmelina arborea,Lamiaceae,Seed,Hydroalcoholic,Reflux,Winter,69,2,9.5,14.11,9.52,22.57,129.65,56.76,72.35,5.745,17.78,Medium,Active
190,PG191,Tinospora cordifolia,Menispermaceae,Stem,Methanol,Soxhlet,Winter,69,3,13.8,17.34,3.09,22.38,98.14,6.70,80.07,4.826,17.23,Low,Active
191,PG192,Bacopa monnieri,Plantaginaceae,Bark,Hydroalcoholic,Reflux,Summer,43,8,9.2,16.71,8.51,27.48,44.11,16.99,92.95,4.873,17.46,Medium,Active
195,PG196,Aloe vera,Asphodelaceae,Stem,Water,Maceration,Summer,62,8,10.9,5.44,11.01,16.71,138.95,94.93,93.87,6.018,17.31,Medium,Active
198,PG199,Withania somnifera,Solanaceae,Stem,Ethanol,Reflux,Winter,62,8,17.0,10.75,10.69,14.04,44.25,58.01,87.40,5.510,20.68,Medium,Active

,Sample_ID,Plant_Name,Family,Plant_Part,Solvent,Extraction_Method,Collection_Season,Temperature_C,Extraction_Time_h,Solvent_to_Drug_Ratio,Moisture_Content_pct,Ash_Value_pct,Extractive_Value_pct,Total_Phenolic_Content_mg_GAE_g,Total_Flavonoid_Content_mg_QE_g,Antioxidant_Activity_pct,Marker_Compound_pct,Extraction_Yield_pct,Quality_Class,Antioxidant_Class
97,PG098,Bacopa monnieri,Plantaginaceae,Root,Methanol,Reflux,Winter,67,8,19.3,4.26,8.63,13.57,64.7,40.81,85.65,1.965,25.32,Low,Active

**Meaning of Code Block 6**

This code block demonstrates how to filter rows from a DataFrame according to specific conditions. Pandas allows us to select only the records that satisfy a particular criterion, such as extraction yield greater than 25%, samples extracted using ethanol, or antioxidant activity of at least 60%. Multiple conditions can also be combined using operators such as & for AND and | for OR. Filtering is an important data-handling operation because it allows researchers to focus on specific samples or conditions during exploratory analysis and subsequent machine-learning workflows.

In [7]:
# Block 7: Selecting Rows and Columns Using loc

# Select specific rows and columns by column names
display(df.loc[0:4, ["Plant_Name", "Plant_Part", "Solvent", "Extraction_Yield_pct"]])

# Select samples with extraction yield greater than 25%
display(df.loc[df["Extraction_Yield_pct"] > 25, ["Plant_Name", "Solvent", "Extraction_Yield_pct"]])

# Select samples with high antioxidant activity and display selected columns
display(df.loc[
    df["Antioxidant_Activity_pct"] >= 60,
    ["Plant_Name", "Total_Phenolic_Content_mg_GAE_g", "Antioxidant_Activity_pct", "Quality_Class"]
])

             Plant_Name Plant_Part         Solvent  Extraction_Yield_pct
0       Bacopa monnieri       Seed         Ethanol                 13.58
1  Tinospora cordifolia    Rhizome  Hydroalcoholic                 17.45
2             Aloe vera       Leaf  Hydroalcoholic                 17.31
3         Curcuma longa       Leaf        Methanol                 15.17
4       Bacopa monnieri       Stem           Water                 13.38

         Plant_Name   Solvent  Extraction_Yield_pct
97  Bacopa monnieri  Methanol                 25.32

,Plant_Name,Total_Phenolic_Content_mg_GAE_g,Antioxidant_Activity_pct,Quality_Class
4,Bacopa monnieri,70.20,80.88,Low
14,Glycyrrhiza glabra,96.52,78.02,Low
17,Aloe vera,32.79,69.99,Medium
19,Withania somnifera,39.53,87.79,Low
20,Curcuma longa,115.09,61.41,Low
...,...,...,...,...
187,Gmelina arborea,129.65,72.35,Medium
190,Tinospora cordifolia,98.14,80.07,Low
191,Bacopa monnieri,44.11,92.95,Medium
195,Aloe vera,138.95,93.87,Medium
198,Withania somnifera,44.25,87.40,Medium

**Meaning of Code Block 7**

This code block introduces loc, a Pandas method used to select rows and columns by their labels or by conditions. Unlike iloc, which primarily uses integer positions, loc allows us to specify actual column names and apply logical conditions at the same time. Here, we select particular columns for selected rows, extract samples with an extraction yield above 25%, and identify samples with antioxidant activity of at least 60% while displaying only the relevant variables. loc is particularly useful for readable and precise data selection and will become important when we modify or preprocess specific parts of a dataset.

In [8]:
# Block 8: Adding, Renaming, and Modifying Columns

# Create a new column with a calculated value
df["Phenolic_Flavonoid_Total"] = (
    df["Total_Phenolic_Content_mg_GAE_g"] +
    df["Total_Flavonoid_Content_mg_QE_g"]
)

# Create a new categorical column based on extraction yield
df["Yield_Category"] = pd.cut(
    df["Extraction_Yield_pct"],
    bins=[0, 15, 25, 50],
    labels=["Low", "Medium", "High"]
)

# Rename a column
df.rename(
    columns={"Temperature_C": "Extraction_Temperature_C"},
    inplace=True
)

# Display the modified DataFrame
display(df.head())

,Sample_ID,Plant_Name,Family,Plant_Part,Solvent,Extraction_Method,Collection_Season,Extraction_Temperature_C,Extraction_Time_h,Solvent_to_Drug_Ratio,...,Extractive_Value_pct,Total_Phenolic_Content_mg_GAE_g,Total_Flavonoid_Content_mg_QE_g,Antioxidant_Activity_pct,Marker_Compound_pct,Extraction_Yield_pct,Quality_Class,Antioxidant_Class,Phenolic_Flavonoid_Total,Yield_Category
0,PG001,Bacopa monnieri,Plantaginaceae,Seed,Ethanol,Maceration,Monsoon,51,2,12.6,...,16.02,111.69,59.83,31.59,0.510,13.58,Low,Less_Active,171.52,Low
1,PG002,Tinospora cordifolia,Menispermaceae,Rhizome,Hydroalcoholic,Soxhlet,Winter,43,2,13.9,...,25.53,169.24,88.33,49.06,4.912,17.45,Low,Less_Active,257.57,Medium
2,PG003,Aloe vera,Asphodelaceae,Leaf,Hydroalcoholic,Maceration,Summer,55,8,10.1,...,16.87,112.03,46.21,44.77,7.278,17.31,Low,Less_Active,158.24,Medium
3,PG004,Curcuma longa,Zingiberaceae,Leaf,Methanol,Maceration,Summer,57,3,13.5,...,25.02,96.70,20.28,52.35,2.063,15.17,Low,Less_Active,116.98,Medium
4,PG005,Bacopa monnieri,Plantaginaceae,Stem,Water,Soxhlet,Summer,52,6,18.3,...,24.47,70.20,58.01,80.88,3.863,13.38,Low,Active,128.21,Low

**Meaning of Code Block 8**

This code block demonstrates how to modify a Pandas DataFrame by creating new columns, generating categories from numerical values, and renaming existing columns. The Phenolic_Flavonoid_Total column is created by adding the total phenolic and flavonoid contents, while pd.cut() converts extraction yield into three categories—Low, Medium, and High—according to defined ranges. The rename() function changes the column name Temperature_C to Extraction_Temperature_C, and inplace=True applies the change directly to the existing DataFrame. Creating and modifying variables in this way is an important skill for preparing features and target variables for machine-learning models.

In [10]:
# Block 9: Checking Missing Values and Duplicate Records

# Count missing values in each column
print("Missing values in each column:")
print(df.isnull().sum())

# Calculate percentage of missing values in each column
print("\nPercentage of missing values:")
print((df.isnull().sum() / len(df) * 100).round(2))

# Count the total number of duplicate rows
print("\nNumber of duplicate rows:")
print(df.duplicated().sum())

# Display rows containing missing values
print("\nRows containing missing values:")
display(df[df.isnull().any(axis=1)])

Missing values in each column:
Sample_ID                          0
Plant_Name                         0
Family                             0
Plant_Part                         0
Solvent                            0
Extraction_Method                  0
Collection_Season                  0
Extraction_Temperature_C           0
Extraction_Time_h                  0
Solvent_to_Drug_Ratio              0
Moisture_Content_pct               4
Ash_Value_pct                      0
Extractive_Value_pct               0
Total_Phenolic_Content_mg_GAE_g    4
Total_Flavonoid_Content_mg_QE_g    0
Antioxidant_Activity_pct           0
Marker_Compound_pct                4
Extraction_Yield_pct               0
Quality_Class                      0
Antioxidant_Class                  0
Phenolic_Flavonoid_Total           4
Yield_Category                     0
dtype: int64

Percentage of missing values:
Sample_ID                          0.0
Plant_Name                         0.0
Family                             0.0
Plant_Part                         0.0
Solvent                            0.0
Extraction_Method                  0.0
Collection_Season                  0.0
Extraction_Temperature_C           0.0
Extraction_Time_h                  0.0
Solvent_to_Drug_Ratio              0.0
Moisture_Content_pct               2.0
Ash_Value_pct                      0.0
Extractive_Value_pct               0.0
Total_Phenolic_Content_mg_GAE_g    2.0
Total_Flavonoid_Content_mg_QE_g    0.0
Antioxidant_Activity_pct           0.0
Marker_Compound_pct                2.0
Extraction_Yield_pct               0.0
Quality_Class                      0.0
Antioxidant_Class                  0.0
Phenolic_Flavonoid_Total           2.0
Yield_Category                     0.0
dtype: float64

Number of duplicate rows:
0

Rows containing missing values:

,Sample_ID,Plant_Name,Family,Plant_Part,Solvent,Extraction_Method,Collection_Season,Extraction_Temperature_C,Extraction_Time_h,Solvent_to_Drug_Ratio,...,Extractive_Value_pct,Total_Phenolic_Content_mg_GAE_g,Total_Flavonoid_Content_mg_QE_g,Antioxidant_Activity_pct,Marker_Compound_pct,Extraction_Yield_pct,Quality_Class,Antioxidant_Class,Phenolic_Flavonoid_Total,Yield_Category
13,PG014,Ocimum tenuiflorum,Lamiaceae,Rhizome,Methanol,Reflux,Monsoon,32,8,7.1,...,12.55,NaN,75.52,49.97,6.862,15.05,Low,Less_Active,NaN,Medium
23,PG024,Glycyrrhiza glabra,Fabaceae,Rhizome,Methanol,Ultrasound,Summer,80,7,15.6,...,12.02,64.44,6.05,36.62,NaN,23.48,Low,Less_Active,70.49,Medium
30,PG031,Moringa oleifera,Moringaceae,Rhizome,Ethanol,Maceration,Winter,46,5,17.5,...,27.32,110.31,52.69,27.34,0.431,18.51,Low,Less_Active,163.00,Medium
63,PG064,Gmelina arborea,Lamiaceae,Leaf,Methanol,Soxhlet,Monsoon,74,9,6.6,...,19.46,NaN,83.39,88.09,3.419,19.03,Medium,Active,NaN,Medium
71,PG072,Curcuma longa,Zingiberaceae,Bark,Methanol,Reflux,Winter,77,2,13.6,...,21.91,153.49,81.13,32.91,NaN,15.25,Low,Less_Active,234.62,Medium
87,PG088,Azadirachta indica,Meliaceae,Seed,Ethanol,Soxhlet,Monsoon,35,10,19.2,...,12.04,118.25,20.70,32.44,NaN,21.70,Low,Less_Active,138.95,Medium
107,PG108,Aloe vera,Asphodelaceae,Stem,Hydroalcoholic,Ultrasound,Monsoon,34,10,6.1,...,20.04,92.10,79.12,29.14,3.265,21.08,Low,Less_Active,171.22,Medium
126,PG127,Tinospora cordifolia,Menispermaceae,Rhizome,Water,Maceration,Winter,72,2,19.7,...,9.89,NaN,30.47,74.54,4.726,14.56,Low,Active,NaN,Low
153,PG154,Aloe vera,Asphodelaceae,Bark,Methanol,Reflux,Winter,78,7,18.3,...,18.33,118.64,96.90,48.13,1.382,20.83,Low,Less_Active,215.54,Medium
155,PG156,Curcuma longa,Zingiberaceae,Root,Methanol,Ultrasound,Winter,73,9,11.6,...,34.30,27.00,7.09,94.23,NaN,24.89,Medium,Active,34.09,Medium
164,PG165,Azadirachta indica,Meliaceae,Bark,Ethanol,Ultrasound,Monsoon,30,2,18.1,...,31.35,NaN,56.54,71.12,6.649,13.41,Medium,Active,NaN,Low
177,PG178,Withania somnifera,Solanaceae,Root,Hydroalcoholic,Reflux,Monsoon,34,5,12.2,...,15.55,139.71,76.18,88.75,1.817,14.38,Low,Active,215.89,Low

**Meaning of Code Block 9**

This code block is used to identify common data-quality problems before machine-learning analysis. df.isnull().sum() counts the missing values in every column, while dividing this count by the total number of rows and multiplying by 100 calculates the percentage of missing values. df.duplicated().sum() identifies the number of completely duplicated rows, and df[df.isnull().any(axis=1)] displays all records containing at least one missing value. Detecting missing and duplicate data is an essential part of data preparation because unsuitable or incomplete records can affect statistical analysis and machine-learning model performance.

In [11]:
# Block 10: Basic Statistical Summary of the Dataset

# Generate descriptive statistics for numerical columns
print("Statistical summary of numerical columns:")
display(df.describe())

# Generate descriptive statistics for all columns
print("\nStatistical summary of all columns:")
display(df.describe(include="all"))

# Calculate the mean of numerical columns
print("\nMean values:")
display(df.mean(numeric_only=True))

# Calculate the median of numerical columns
print("\nMedian values:")
display(df.median(numeric_only=True))

Statistical summary of numerical columns:

,Extraction_Temperature_C,Extraction_Time_h,Solvent_to_Drug_Ratio,Moisture_Content_pct,Ash_Value_pct,Extractive_Value_pct,Total_Phenolic_Content_mg_GAE_g,Total_Flavonoid_Content_mg_QE_g,Antioxidant_Activity_pct,Marker_Compound_pct,Extraction_Yield_pct,Phenolic_Flavonoid_Total
count,200.000000,200.000000,200.00000,196.000000,200.000000,200.000000,196.000000,200.000000,200.000000,196.000000,200.00000,196.000000
mean,54.440000,6.905000,12.77600,11.167755,7.062900,21.208900,96.881582,53.122600,58.873250,4.123372,18.38015,149.833622
std,14.879631,3.194841,4.31642,4.376808,2.757202,7.196473,46.493921,27.522495,21.177348,2.192567,3.08465,57.881756
min,30.000000,2.000000,5.00000,4.010000,2.090000,8.030000,20.050000,5.180000,25.010000,0.216000,10.07000,34.090000
25%,41.000000,4.000000,9.65000,7.190000,4.965000,14.940000,56.415000,26.570000,40.735000,2.211000,16.31750,109.622500
50%,54.000000,7.000000,12.85000,11.325000,7.270000,21.720000,96.880000,56.650000,56.250000,4.267500,18.39000,147.075000
75%,67.000000,9.000000,16.25000,15.460000,9.265000,26.277500,137.090000,76.400000,78.052500,5.989500,20.77000,191.812500
max,80.000000,12.000000,20.00000,17.950000,11.930000,34.880000,178.790000,99.160000,94.800000,7.998000,25.32000,276.260000

Statistical summary of all columns:

,Sample_ID,Plant_Name,Family,Plant_Part,Solvent,Extraction_Method,Collection_Season,Extraction_Temperature_C,Extraction_Time_h,Solvent_to_Drug_Ratio,...,Extractive_Value_pct,Total_Phenolic_Content_mg_GAE_g,Total_Flavonoid_Content_mg_QE_g,Antioxidant_Activity_pct,Marker_Compound_pct,Extraction_Yield_pct,Quality_Class,Antioxidant_Class,Phenolic_Flavonoid_Total,Yield_Category
count,200,200,200,200,200,200,200,200.000000,200.000000,200.00000,...,200.000000,196.000000,200.000000,200.000000,196.000000,200.00000,200,200,196.000000,200
unique,200,10,9,6,4,4,3,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2,2,NaN,3
top,PG001,Bacopa monnieri,Lamiaceae,Leaf,Ethanol,Maceration,Summer,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Low,Less_Active,NaN,Medium
freq,1,26,38,39,57,59,75,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,143,108,NaN,173
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.440000,6.905000,12.77600,...,21.208900,96.881582,53.122600,58.873250,4.123372,18.38015,NaN,NaN,149.833622,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.879631,3.194841,4.31642,...,7.196473,46.493921,27.522495,21.177348,2.192567,3.08465,NaN,NaN,57.881756,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.000000,2.000000,5.00000,...,8.030000,20.050000,5.180000,25.010000,0.216000,10.07000,NaN,NaN,34.090000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.000000,4.000000,9.65000,...,14.940000,56.415000,26.570000,40.735000,2.211000,16.31750,NaN,NaN,109.622500,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.000000,7.000000,12.85000,...,21.720000,96.880000,56.650000,56.250000,4.267500,18.39000,NaN,NaN,147.075000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,67.000000,9.000000,16.25000,...,26.277500,137.090000,76.400000,78.052500,5.989500,20.77000,NaN,NaN,191.812500,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.000000,12.000000,20.00000,...,34.880000,178.790000,99.160000,94.800000,7.998000,25.32000,NaN,NaN,276.260000,NaN

Mean values:

Extraction_Temperature_C            54.440000
Extraction_Time_h                    6.905000
Solvent_to_Drug_Ratio               12.776000
Moisture_Content_pct                11.167755
Ash_Value_pct                        7.062900
Extractive_Value_pct                21.208900
Total_Phenolic_Content_mg_GAE_g     96.881582
Total_Flavonoid_Content_mg_QE_g     53.122600
Antioxidant_Activity_pct            58.873250
Marker_Compound_pct                  4.123372
Extraction_Yield_pct                18.380150
Phenolic_Flavonoid_Total           149.833622
dtype: float64

Median values:

Extraction_Temperature_C            54.0000
Extraction_Time_h                    7.0000
Solvent_to_Drug_Ratio               12.8500
Moisture_Content_pct                11.3250
Ash_Value_pct                        7.2700
Extractive_Value_pct                21.7200
Total_Phenolic_Content_mg_GAE_g     96.8800
Total_Flavonoid_Content_mg_QE_g     56.6500
Antioxidant_Activity_pct            56.2500
Marker_Compound_pct                  4.2675
Extraction_Yield_pct                18.3900
Phenolic_Flavonoid_Total           147.0750
dtype: float64

**Meaning of Code Block 10**

This code block performs basic statistical analysis of the dataset. df.describe() provides important descriptive statistics for numerical variables, including count, mean, standard deviation, minimum, quartiles, and maximum values, while df.describe(include="all") extends the summary to categorical columns as well. The mean() and median() functions calculate the average and middle values of numerical variables, respectively. These statistics help us understand the distribution, central tendency, variability, and general characteristics of the Pharmacognosy data before applying machine-learning algorithms.

In [12]:
# Block 11: Counting and Summarizing Categorical Data

# Count unique values in selected categorical columns
print("Number of unique plant species:")
print(df["Plant_Name"].nunique())

print("\nNumber of unique extraction methods:")
print(df["Extraction_Method"].nunique())

# Display frequency of each plant species
print("\nPlant species frequency:")
display(df["Plant_Name"].value_counts())

# Display frequency of extraction methods
print("\nExtraction method frequency:")
display(df["Extraction_Method"].value_counts())

# Display frequency of quality classes
print("\nQuality class frequency:")
display(df["Quality_Class"].value_counts())

Number of unique plant species:
10

Number of unique extraction methods:
4

Plant species frequency:

Plant_Name
Bacopa monnieri         26
Aloe vera               23
Azadirachta indica      23
Moringa oleifera        20
Curcuma longa           20
Ocimum tenuiflorum      19
Gmelina arborea         19
Tinospora cordifolia    18
Withania somnifera      17
Glycyrrhiza glabra      15
Name: count, dtype: int64

Extraction method frequency:

Extraction_Method
Maceration    59
Reflux        53
Ultrasound    45
Soxhlet       43
Name: count, dtype: int64

Quality class frequency:

Quality_Class
Low       143
Medium     57
Name: count, dtype: int64

**Meaning of Code Block 11**

This code block is used to examine categorical variables and understand how frequently different categories occur in the dataset. The nunique() function counts the number of distinct values in a column, while value_counts() counts how many times each individual category appears. Here, we examine the number and distribution of plant species, extraction methods, and quality classes. Understanding categorical distributions is important because it helps identify the composition of the dataset and, later, determine whether classification targets are reasonably balanced or dominated by particular classes.

In [13]:
# Block 12: Sorting and Ranking Data

# Sort the dataset by extraction yield in ascending order
df_sorted_ascending = df.sort_values(
    by="Extraction_Yield_pct",
    ascending=True
)

print("Samples with lowest extraction yield:")
display(df_sorted_ascending[[
    "Plant_Name",
    "Solvent",
    "Extraction_Method",
    "Extraction_Yield_pct"
]].head(10))

# Sort the dataset by extraction yield in descending order
df_sorted_descending = df.sort_values(
    by="Extraction_Yield_pct",
    ascending=False
)

print("\nSamples with highest extraction yield:")
display(df_sorted_descending[[
    "Plant_Name",
    "Solvent",
    "Extraction_Method",
    "Extraction_Yield_pct"
]].head(10))

# Sort by more than one column
print("\nSorted by extraction method and extraction yield:")
display(
    df.sort_values(
        by=["Extraction_Method", "Extraction_Yield_pct"],
        ascending=[True, False]
    )[[
        "Plant_Name",
        "Extraction_Method",
        "Extraction_Yield_pct"
    ]].head(15)
)

Samples with lowest extraction yield:

             Plant_Name   Solvent Extraction_Method  Extraction_Yield_pct
146    Moringa oleifera     Water        Maceration                 10.07
132  Ocimum tenuiflorum   Ethanol        Maceration                 10.63
196       Curcuma longa   Ethanol        Maceration                 12.01
144  Azadirachta indica     Water        Maceration                 12.38
37      Bacopa monnieri     Water        Maceration                 12.39
172       Curcuma longa   Ethanol        Maceration                 12.51
174           Aloe vera  Methanol            Reflux                 12.74
124  Azadirachta indica   Ethanol        Maceration                 12.78
99            Aloe vera     Water        Ultrasound                 12.90
85            Aloe vera  Methanol        Maceration                 13.24

Samples with highest extraction yield:

,Plant_Name,Solvent,Extraction_Method,Extraction_Yield_pct
97,Bacopa monnieri,Methanol,Reflux,25.32
155,Curcuma longa,Methanol,Ultrasound,24.89
48,Bacopa monnieri,Hydroalcoholic,Ultrasound,24.84
183,Azadirachta indica,Hydroalcoholic,Maceration,24.80
199,Glycyrrhiza glabra,Water,Ultrasound,24.49
98,Moringa oleifera,Methanol,Ultrasound,24.15
104,Aloe vera,Ethanol,Ultrasound,23.80
59,Gmelina arborea,Methanol,Ultrasound,23.75
53,Withania somnifera,Ethanol,Ultrasound,23.69
58,Glycyrrhiza glabra,Hydroalcoholic,Soxhlet,23.64

Sorted by extraction method and extraction yield:

               Plant_Name Extraction_Method  Extraction_Yield_pct
183    Azadirachta indica        Maceration                 24.80
16     Withania somnifera        Maceration                 22.49
55   Tinospora cordifolia        Maceration                 21.87
122    Ocimum tenuiflorum        Maceration                 21.47
73          Curcuma longa        Maceration                 20.98
133    Glycyrrhiza glabra        Maceration                 20.96
89     Ocimum tenuiflorum        Maceration                 20.71
31     Ocimum tenuiflorum        Maceration                 20.49
66   Tinospora cordifolia        Maceration                 19.75
160    Glycyrrhiza glabra        Maceration                 19.75
9           Curcuma longa        Maceration                 19.61
34        Bacopa monnieri        Maceration                 19.54
44        Gmelina arborea        Maceration                 19.43
93        Gmelina arborea        Maceration                 18.85
12              Aloe vera        Maceration                 18.78

**Meaning of Code Block 12**

This code block demonstrates how to sort and rank records in a Pandas DataFrame. The sort_values() function arranges records according to one or more columns, while ascending=True sorts values from lowest to highest and ascending=False sorts them from highest to lowest. Here, we identify samples with the lowest and highest extraction yields and also demonstrate multi-column sorting by extraction method followed by extraction yield. Sorting is useful for quickly identifying high- or low-performing samples, comparing experimental conditions, and organizing data before further analysis.

In [14]:
# Block 13: Grouping Data and Calculating Summary Statistics

# Calculate average extraction yield for each extraction method
print("Average extraction yield by extraction method:")
display(
    df.groupby("Extraction_Method")["Extraction_Yield_pct"]
      .mean()
      .sort_values(ascending=False)
)

# Calculate average antioxidant activity for each solvent
print("\nAverage antioxidant activity by solvent:")
display(
    df.groupby("Solvent")["Antioxidant_Activity_pct"]
      .mean()
      .sort_values(ascending=False)
)

# Calculate multiple statistics for extraction yield by plant part
print("\nExtraction yield statistics by plant part:")
display(
    df.groupby("Plant_Part")["Extraction_Yield_pct"]
      .agg(["count", "mean", "min", "max"])
      .sort_values("mean", ascending=False)
)

Average extraction yield by extraction method:

Extraction_Method
Ultrasound    19.938889
Soxhlet       18.658605
Reflux        18.556415
Maceration    16.830000
Name: Extraction_Yield_pct, dtype: float64

Average antioxidant activity by solvent:

Solvent
Ethanol           61.921228
Hydroalcoholic    59.843148
Water             57.887073
Methanol          55.005000
Name: Antioxidant_Activity_pct, dtype: float64

Extraction yield statistics by plant part:

            count       mean    min    max
Plant_Part
Rhizome        35  18.878857  12.38  24.84
Stem           38  18.662632  12.01  23.80
Seed           36  18.379722  12.74  24.80
Leaf           39  18.354103  10.63  23.09
Root           28  17.877143  10.07  25.32
Bark           24  17.835417  13.41  24.15

**Meaning of Code Block 13**

This code block demonstrates how to group records according to a categorical variable and calculate summary statistics for each group. The groupby() function divides the dataset into groups such as extraction methods, solvents, or plant parts, and functions such as mean() calculate the average value within each group. The agg() function allows several statistics, including count, mean, minimum, and maximum, to be calculated simultaneously. Grouping is particularly useful in Pharmacognosy because it allows us to compare outcomes such as extraction yield or antioxidant activity across different extraction methods, solvents, and plant materials.

In [15]:
# Block 14: Removing and Restoring a Column

# Create a temporary copy of the DataFrame
df_temp = df.copy()

# Remove the temporary calculated column
df_temp.drop(columns=["Phenolic_Flavonoid_Total"], inplace=True)

print("Columns after removing Phenolic_Flavonoid_Total:")
print(df_temp.columns.tolist())

# Restore the calculated column
df_temp["Phenolic_Flavonoid_Total"] = (
    df_temp["Total_Phenolic_Content_mg_GAE_g"] +
    df_temp["Total_Flavonoid_Content_mg_QE_g"]
)

print("\nColumns after restoring the column:")
print(df_temp.columns.tolist())

display(df_temp.head())

Columns after removing Phenolic_Flavonoid_Total:
['Sample_ID', 'Plant_Name', 'Family', 'Plant_Part', 'Solvent', 'Extraction_Method', 'Collection_Season', 'Extraction_Temperature_C', 'Extraction_Time_h', 'Solvent_to_Drug_Ratio', 'Moisture_Content_pct', 'Ash_Value_pct', 'Extractive_Value_pct', 'Total_Phenolic_Content_mg_GAE_g', 'Total_Flavonoid_Content_mg_QE_g', 'Antioxidant_Activity_pct', 'Marker_Compound_pct', 'Extraction_Yield_pct', 'Quality_Class', 'Antioxidant_Class', 'Yield_Category']

Columns after restoring the column:
['Sample_ID', 'Plant_Name', 'Family', 'Plant_Part', 'Solvent', 'Extraction_Method', 'Collection_Season', 'Extraction_Temperature_C', 'Extraction_Time_h', 'Solvent_to_Drug_Ratio', 'Moisture_Content_pct', 'Ash_Value_pct', 'Extractive_Value_pct', 'Total_Phenolic_Content_mg_GAE_g', 'Total_Flavonoid_Content_mg_QE_g', 'Antioxidant_Activity_pct', 'Marker_Compound_pct', 'Extraction_Yield_pct', 'Quality_Class', 'Antioxidant_Class', 'Yield_Category', 'Phenolic_Flavonoid_Total']

,Sample_ID,Plant_Name,Family,Plant_Part,Solvent,Extraction_Method,Collection_Season,Extraction_Temperature_C,Extraction_Time_h,Solvent_to_Drug_Ratio,...,Extractive_Value_pct,Total_Phenolic_Content_mg_GAE_g,Total_Flavonoid_Content_mg_QE_g,Antioxidant_Activity_pct,Marker_Compound_pct,Extraction_Yield_pct,Quality_Class,Antioxidant_Class,Yield_Category,Phenolic_Flavonoid_Total
0,PG001,Bacopa monnieri,Plantaginaceae,Seed,Ethanol,Maceration,Monsoon,51,2,12.6,...,16.02,111.69,59.83,31.59,0.510,13.58,Low,Less_Active,Low,171.52
1,PG002,Tinospora cordifolia,Menispermaceae,Rhizome,Hydroalcoholic,Soxhlet,Winter,43,2,13.9,...,25.53,169.24,88.33,49.06,4.912,17.45,Low,Less_Active,Medium,257.57
2,PG003,Aloe vera,Asphodelaceae,Leaf,Hydroalcoholic,Maceration,Summer,55,8,10.1,...,16.87,112.03,46.21,44.77,7.278,17.31,Low,Less_Active,Medium,158.24
3,PG004,Curcuma longa,Zingiberaceae,Leaf,Methanol,Maceration,Summer,57,3,13.5,...,25.02,96.70,20.28,52.35,2.063,15.17,Low,Less_Active,Medium,116.98
4,PG005,Bacopa monnieri,Plantaginaceae,Stem,Water,Soxhlet,Summer,52,6,18.3,...,24.47,70.20,58.01,80.88,3.863,13.38,Low,Active,Low,128.21

**Meaning of Code Block 14**

This code block demonstrates how to remove and recreate a column in a Pandas DataFrame without permanently changing our original master dataset. df.copy() creates an independent copy called df_temp, and drop() removes the selected column from this temporary DataFrame. We then recreate the same column using the original numerical variables. Using a temporary copy is a good practice during learning because it allows us to experiment with DataFrame operations while protecting the original dataset that will be used throughout our machine-learning practicals.

In [16]:
# Block 15: Working with DataFrame Copies

# Create a copy of the original DataFrame
df_copy = df.copy()

# Modify the copied DataFrame
df_copy["Extraction_Yield_pct"] = df_copy["Extraction_Yield_pct"].round(1)

# Compare the original and copied DataFrame
print("Original DataFrame:")
display(df[["Sample_ID", "Extraction_Yield_pct"]].head())

print("\nCopied DataFrame:")
display(df_copy[["Sample_ID", "Extraction_Yield_pct"]].head())

# Check whether both DataFrames are the same object
print("\nAre df and df_copy the same object?")
print(df is df_copy)

Original DataFrame:

  Sample_ID  Extraction_Yield_pct
0     PG001                 13.58
1     PG002                 17.45
2     PG003                 17.31
3     PG004                 15.17
4     PG005                 13.38

Copied DataFrame:

  Sample_ID  Extraction_Yield_pct
0     PG001                  13.6
1     PG002                  17.4
2     PG003                  17.3
3     PG004                  15.2
4     PG005                  13.4

Are df and df_copy the same object?
False

**Meaning of Code Block 15**

This code block demonstrates the importance of creating an independent copy of a DataFrame before making experimental changes. df.copy() creates a separate DataFrame called df_copy, allowing us to modify values without unintentionally changing the original df dataset. Here, the extraction-yield values in the copied DataFrame are rounded to one decimal place, while the original values remain unchanged. The expression df is df_copy checks whether both variables refer to the same Python object and returns False, confirming that the copy is independent. This practice is particularly important in machine-learning workflows where the original dataset should be preserved for reproducibility and comparison.

In [17]:
# Block 16: Removing Duplicate Records and Resetting the Index

# Create a working copy of the DataFrame
df_clean = df.copy()

# Count duplicate records
duplicate_count = df_clean.duplicated().sum()

print("Number of duplicate records:", duplicate_count)

# Remove duplicate records
df_clean = df_clean.drop_duplicates()

# Reset the DataFrame index after removing duplicates
df_clean = df_clean.reset_index(drop=True)

# Display the updated shape
print("Shape after removing duplicates:", df_clean.shape)

# Display the first five records
display(df_clean.head())

Number of duplicate records: 0
Shape after removing duplicates: (200, 22)

,Sample_ID,Plant_Name,Family,Plant_Part,Solvent,Extraction_Method,Collection_Season,Extraction_Temperature_C,Extraction_Time_h,Solvent_to_Drug_Ratio,...,Extractive_Value_pct,Total_Phenolic_Content_mg_GAE_g,Total_Flavonoid_Content_mg_QE_g,Antioxidant_Activity_pct,Marker_Compound_pct,Extraction_Yield_pct,Quality_Class,Antioxidant_Class,Phenolic_Flavonoid_Total,Yield_Category
0,PG001,Bacopa monnieri,Plantaginaceae,Seed,Ethanol,Maceration,Monsoon,51,2,12.6,...,16.02,111.69,59.83,31.59,0.510,13.58,Low,Less_Active,171.52,Low
1,PG002,Tinospora cordifolia,Menispermaceae,Rhizome,Hydroalcoholic,Soxhlet,Winter,43,2,13.9,...,25.53,169.24,88.33,49.06,4.912,17.45,Low,Less_Active,257.57,Medium
2,PG003,Aloe vera,Asphodelaceae,Leaf,Hydroalcoholic,Maceration,Summer,55,8,10.1,...,16.87,112.03,46.21,44.77,7.278,17.31,Low,Less_Active,158.24,Medium
3,PG004,Curcuma longa,Zingiberaceae,Leaf,Methanol,Maceration,Summer,57,3,13.5,...,25.02,96.70,20.28,52.35,2.063,15.17,Low,Less_Active,116.98,Medium
4,PG005,Bacopa monnieri,Plantaginaceae,Stem,Water,Soxhlet,Summer,52,6,18.3,...,24.47,70.20,58.01,80.88,3.863,13.38,Low,Active,128.21,Low

**Meaning of Code Block 16**

This code block demonstrates how to identify and remove duplicate records while preserving the original dataset. A copy of the DataFrame is first created as df_clean, after which duplicated().sum() counts completely duplicated rows. The drop_duplicates() function removes those duplicate records, and reset_index(drop=True) creates a new continuous index after the removal. Working with a separate copy is important because it protects the original master dataset and allows us to perform data-cleaning operations safely.

In [18]:
# Block 17: Saving the DataFrame as an Excel File

# Save the current DataFrame as a new Excel file
output_file = "Pharmacognosy_ML_Processed_Data.xlsx"

df_clean.to_excel(output_file, index=False)

# Confirm that the file has been saved
print("File saved successfully as:", output_file)

File saved successfully as: Pharmacognosy_ML_Processed_Data.xlsx

**Meaning of Code Block 17**

This code block demonstrates how to export a Pandas DataFrame into an Excel file. The variable output_file stores the desired filename, and df_clean.to_excel() converts the DataFrame into an Excel workbook. The argument index=False prevents Pandas from adding the DataFrame index as an unnecessary additional column in the Excel file. Saving processed data is an important skill because it allows the cleaned or modified dataset to be reused for further analysis, documentation, and machine-learning workflows.

In [19]:
# Block 18: Final Inspection of the DataFrame

print("Final dataset shape:")
print(df_clean.shape)

print("\nFinal column names:")
print(df_clean.columns.tolist())

print("\nMissing values:")
print(df_clean.isnull().sum())

print("\nDuplicate records:")
print(df_clean.duplicated().sum())

print("\nFinal statistical summary:")
display(df_clean.describe())

print("\nFirst five records:")
display(df_clean.head())

Final dataset shape:
(200, 22)

Final column names:
['Sample_ID', 'Plant_Name', 'Family', 'Plant_Part', 'Solvent', 'Extraction_Method', 'Collection_Season', 'Extraction_Temperature_C', 'Extraction_Time_h', 'Solvent_to_Drug_Ratio', 'Moisture_Content_pct', 'Ash_Value_pct', 'Extractive_Value_pct', 'Total_Phenolic_Content_mg_GAE_g', 'Total_Flavonoid_Content_mg_QE_g', 'Antioxidant_Activity_pct', 'Marker_Compound_pct', 'Extraction_Yield_pct', 'Quality_Class', 'Antioxidant_Class', 'Phenolic_Flavonoid_Total', 'Yield_Category']

Missing values:
Sample_ID                          0
Plant_Name                         0
Family                             0
Plant_Part                         0
Solvent                            0
Extraction_Method                  0
Collection_Season                  0
Extraction_Temperature_C           0
Extraction_Time_h                  0
Solvent_to_Drug_Ratio              0
Moisture_Content_pct               4
Ash_Value_pct                      0
Extractive_Value_pct               0
Total_Phenolic_Content_mg_GAE_g    4
Total_Flavonoid_Content_mg_QE_g    0
Antioxidant_Activity_pct           0
Marker_Compound_pct                4
Extraction_Yield_pct               0
Quality_Class                      0
Antioxidant_Class                  0
Phenolic_Flavonoid_Total           4
Yield_Category                     0
dtype: int64

Duplicate records:
0

Final statistical summary:

,Extraction_Temperature_C,Extraction_Time_h,Solvent_to_Drug_Ratio,Moisture_Content_pct,Ash_Value_pct,Extractive_Value_pct,Total_Phenolic_Content_mg_GAE_g,Total_Flavonoid_Content_mg_QE_g,Antioxidant_Activity_pct,Marker_Compound_pct,Extraction_Yield_pct,Phenolic_Flavonoid_Total
count,200.000000,200.000000,200.00000,196.000000,200.000000,200.000000,196.000000,200.000000,200.000000,196.000000,200.00000,196.000000
mean,54.440000,6.905000,12.77600,11.167755,7.062900,21.208900,96.881582,53.122600,58.873250,4.123372,18.38015,149.833622
std,14.879631,3.194841,4.31642,4.376808,2.757202,7.196473,46.493921,27.522495,21.177348,2.192567,3.08465,57.881756
min,30.000000,2.000000,5.00000,4.010000,2.090000,8.030000,20.050000,5.180000,25.010000,0.216000,10.07000,34.090000
25%,41.000000,4.000000,9.65000,7.190000,4.965000,14.940000,56.415000,26.570000,40.735000,2.211000,16.31750,109.622500
50%,54.000000,7.000000,12.85000,11.325000,7.270000,21.720000,96.880000,56.650000,56.250000,4.267500,18.39000,147.075000
75%,67.000000,9.000000,16.25000,15.460000,9.265000,26.277500,137.090000,76.400000,78.052500,5.989500,20.77000,191.812500
max,80.000000,12.000000,20.00000,17.950000,11.930000,34.880000,178.790000,99.160000,94.800000,7.998000,25.32000,276.260000

First five records:

,Sample_ID,Plant_Name,Family,Plant_Part,Solvent,Extraction_Method,Collection_Season,Extraction_Temperature_C,Extraction_Time_h,Solvent_to_Drug_Ratio,...,Extractive_Value_pct,Total_Phenolic_Content_mg_GAE_g,Total_Flavonoid_Content_mg_QE_g,Antioxidant_Activity_pct,Marker_Compound_pct,Extraction_Yield_pct,Quality_Class,Antioxidant_Class,Phenolic_Flavonoid_Total,Yield_Category
0,PG001,Bacopa monnieri,Plantaginaceae,Seed,Ethanol,Maceration,Monsoon,51,2,12.6,...,16.02,111.69,59.83,31.59,0.510,13.58,Low,Less_Active,171.52,Low
1,PG002,Tinospora cordifolia,Menispermaceae,Rhizome,Hydroalcoholic,Soxhlet,Winter,43,2,13.9,...,25.53,169.24,88.33,49.06,4.912,17.45,Low,Less_Active,257.57,Medium
2,PG003,Aloe vera,Asphodelaceae,Leaf,Hydroalcoholic,Maceration,Summer,55,8,10.1,...,16.87,112.03,46.21,44.77,7.278,17.31,Low,Less_Active,158.24,Medium
3,PG004,Curcuma longa,Zingiberaceae,Leaf,Methanol,Maceration,Summer,57,3,13.5,...,25.02,96.70,20.28,52.35,2.063,15.17,Low,Less_Active,116.98,Medium
4,PG005,Bacopa monnieri,Plantaginaceae,Stem,Water,Soxhlet,Summer,52,6,18.3,...,24.47,70.20,58.01,80.88,3.863,13.38,Low,Active,128.21,Low

**Meaning of Code Block 18**

This code block performs a final inspection of the working DataFrame before we proceed to subsequent machine-learning practicals. It checks the final number of rows and columns using shape, confirms the available variables using columns.tolist(), identifies remaining missing values using isnull().sum(), verifies whether duplicate records remain using duplicated().sum(), provides a statistical summary of numerical variables using describe(), and displays the first five records for a final visual check. This type of final dataset inspection is an important reproducibility and quality-control step before moving from basic Pandas operations to dedicated data preprocessing and machine-learning workflows.